accounts/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',

    url( r'^new_account$', 'accounts.views.new_account', name= 'new_account' ),
    url( r'^login$', 'accounts.views.login', name= 'login' ),
    url( r'^logout$', 'django.contrib.auth.views.logout', name= 'logout' ),
    url( r'^user/(?P<username>\w+)$', 'accounts.views.user_page', name= 'user_page' ),
    url( r'^set_moderator/(?P<username>\w+)$', 'accounts.views.set_moderator', name= 'set_moderator' ),

        # Remove Account

    url( r'^remove/confirm/(?P<username>\w+)$', 'accounts.views.remove_user_confirm', name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', 'accounts.views.remove_user', name= 'remove' ),

        # Disable Account

   url( r'^disable/confirm/(?P<username>\w+)$', 'accounts.views.disable_user_confirm', name= 'disable_confirm' ),
   url( r'^disable/(?P<username>\w+)$', 'accounts.views.disable_user', name= 'disable' ),

        # Change Password
    url( r'^change_password$', 'django.contrib.auth.views.password_change', { 'template_name': 'accounts/change_password.html', 'post_change_redirect': 'accounts:password_changed' }, name= 'change_password' ),
    url( r'^password_changed$', 'accounts.views.password_changed', name= 'password_changed' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', 'accounts.views.message_send', name= 'message_send' ),
    url( r'^message/all/$', 'accounts.views.message_all', name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', 'accounts.views.message_open', name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', 'accounts.views.message_remove_confirm', name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', 'accounts.views.message_remove', name= 'message_remove' ),
)

forum/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [

    url( r'^$', 'forum.views.index', name= 'index' ),
    url( r'^forum/(?P<forumSlug>[\w-]+)/(?P<page>[0-9]+)$', 'forum.views.sub_forum', name= 'subForum' ),
    url( r'^thread/(?P<threadSlug>[\w-]+)/(?P<page>[0-9]+)$', 'forum.views.open_thread', name= 'thread' ),

    url( r'^new_thread/(?P<forumSlug>[\w-]+)$', 'forum.views.new_thread', name= 'new_thread' ),
    url( r'^new_category$', 'forum.views.new_category', name= 'new_category' ),
    url( r'^new_sub_forum/(?P<categorySlug>[\w-]+)$', 'forum.views.new_sub_forum', name= 'new_sub_forum' ),

    url( r'^lock_thread/(?P<threadSlug>[\w-]+)$', 'forum.views.lock_thread', name= 'lock_thread' ),

    url( r'^edit_post/(?P<postId>\w+)$', 'forum.views.edit_post', name= 'edit_post' ),
    url( r'^edit_thread/(?P<threadSlug>[\w-]+)$', 'forum.views.edit_thread', name= 'edit_thread' ),
    url( r'^edit_category/(?P<categorySlug>[\w-]+)$', 'forum.views.edit_category', name= 'edit_category' ),
    url( r'^edit_sub_forum/(?P<forumSlug>[\w-]+)$', 'forum.views.edit_sub_forum', name= 'edit_sub_forum' ),

    url( r'^remove/post_confirm/(?P<postId>\w+)$', 'forum.views.remove_post_confirm', name= 'remove_post_confirm' ),
    url( r'^remove/post/(?P<postId>\w+)$', 'forum.views.remove_post', name= 'remove_post' ),
    url( r'^remove/thread_confirm/(?P<threadSlug>[\w-]+)$', 'forum.views.remove_thread_confirm', name= 'remove_thread_confirm' ),
    url( r'^remove/thread/(?P<threadSlug>[\w-]+)$', 'forum.views.remove_thread', name= 'remove_thread' ),
    url( r'^remove/sub_forum_confirm/(?P<forumSlug>[\w-]+)$', 'forum.views.remove_sub_forum_confirm', name= 'remove_sub_forum_confirm' ),
    url( r'^remove/sub_forum/(?P<forumSlug>[\w-]+)$', 'forum.views.remove_sub_forum', name= 'remove_sub_forum' ),
    url( r'^remove/category_confirm/(?P<categorySlug>[\w-]+)$', 'forum.views.remove_category_confirm', name= 'remove_category_confirm' ),
    url( r'^remove/category/(?P<categorySlug>[\w-]+)$', 'forum.views.remove_category', name= 'remove_category' ),

    url( r'^users_list$', 'forum.views.users_list', name= 'users_list' ),

    url( r'^accounts/', include( 'accounts.urls', namespace= 'accounts', app_name= 'accounts' ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]


    # Serve static files when debug false
if not settings.DEBUG:
    urlpatterns += [
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT } ),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone
from django.core.urlresolvers import reverse


class Account( AbstractUser ):

    is_moderator = models.BooleanField( default= False )

    def get_url(self):
        return reverse( 'accounts:user_page', args= [ self.username ] )

    def get_post_count(self):
        return self.post_set.all().count()

    def has_moderator_rights(self):
        if self.is_staff or self.is_moderator:
            return True

        return False


class PrivateMessage( models.Model ):

    receiver = models.ForeignKey( settings.AUTH_USER_MODEL )
    sender = models.ForeignKey( settings.AUTH_USER_MODEL, related_name= 'sender' )
    title = models.TextField( max_length= 100 )
    content = models.TextField( max_length= 500 )
    date_created = models.DateTimeField( help_text= 'Date Created', default= timezone.now )

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse( 'accounts:message_open', args= [ self.id ] )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.html import strip_tags


class FixUserCreationForm( UserCreationForm ):
    """
        The django form has the User hard-coded (so doesn't work with custom user models)

        Just change the parts where the User is hard-coded
    """
    def clean_username(self):

        userModel = get_user_model()

        username = self.cleaned_data[ "username" ]

        try:
            userModel.objects.get( username= username )

        except userModel.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])


class MyUserCreationForm( FixUserCreationForm ):

    email = forms.EmailField( required= True )

    class Meta:

        model = get_user_model()
        fields = ( 'username', 'email', 'password1', 'password2' )

    def clean_email( self ):

        """
            Check if there's already an user with that email
        """

        userModel = get_user_model()
        email = self.cleaned_data[ 'email' ]

        try:
            userModel.objects.get( email= email )

        except userModel.DoesNotExist:

            return email

        else:
            raise ValidationError( 'An account with that email already exists.' )



    def save( self, commit= True ):

        user = super( MyUserCreationForm, self ).save( commit= False )
        user.email = self.cleaned_data[ 'email' ]

        if commit:
            user.save()

        return user


class PrivateMessageForm( forms.Form ):

    title = forms.CharField( max_length= 100 )
    content = forms.CharField( max_length= 500, widget= forms.Textarea )

    def clean_title(self):
        return strip_tags( self.cleaned_data[ 'title' ] )

    def clean_content(self):
        return strip_tags( self.cleaned_data[ 'content' ] )

accounts/views.py
from django.contrib.auth import get_user_model
from django.http import Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as django_login

from accounts.forms import MyUserCreationForm, PrivateMessageForm
from accounts.models import PrivateMessage
from accounts.decorators import must_be_staff, must_be_moderator

from forum import utilities


def new_account( request ):

    if request.method == 'POST':

        form = MyUserCreationForm( request.POST )

        if form.is_valid():

            form.save()
            utilities.set_message( request, "User '{}' created!".format( form.cleaned_data[ 'username' ] ) )

            return HttpResponseRedirect( reverse( 'accounts:login' ) )

    else:
        form = MyUserCreationForm()

    context = {
        'form': form
    }

    return render( request, 'accounts/new_account.html', context )


def login( request ):

    context = {}
    utilities.get_message( request, context )

    return django_login( request, 'accounts/login.html', extra_context= context )


def user_page( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    posts = user.post_set.order_by( '-date_created' )
    last_posts = posts[ :5 ]
    total_posts = posts.count()

    threads = user.thread_set.order_by( '-date_created' )
    last_threads = threads[ :5 ]
    total_threads = threads.count()

    context = {
        'pageUser': user,
        'last_posts': last_posts,
        'total_posts': total_posts,
        'last_threads': last_threads,
        'total_threads': total_threads,
    }

    utilities.get_message( request, context )

    return render( request, 'accounts/user_page.html', context )


@login_required
def message_send( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( 'Invalid username.' )


    if request.method == 'POST':
        form = PrivateMessageForm( request.POST )

        if form.is_valid():

            title = form.cleaned_data[ 'title' ]
            content = form.cleaned_data[ 'content' ]
            message = PrivateMessage( receiver= user, sender= request.user, title= title, content= content )
            message.save()

            utilities.set_message( request, 'Message sent to {}!'.format( user.username ) )

            return HttpResponseRedirect( user.get_url() )

    else:
        form = PrivateMessageForm()

    context = {
        'form': form,
        'username': username
    }

    return render( request, 'accounts/send_message.html', context )


@login_required
def message_all( request ):

    messages = request.user.privatemessage_set.all()

    context = {
        'messages': messages
    }

    utilities.get_message( request, context )

    return render( request, 'accounts/check_messages.html', context )


@login_required
def message_open( request, messageId ):

    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Couldn't find that message." )

    context = {
        'private_message': message
    }

    return render( request, 'accounts/open_message.html', context )


@login_required
def message_remove_confirm( request, messageId ):

    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Didn't find the message." )

    else:
        context = {
            'private_message': message
        }

        return render( request, 'accounts/remove_message.html', context )


@login_required
def message_remove( request, messageId ):

    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Message doesn't exist." )

    message.delete()
    utilities.set_message( request, 'Message removed!' )

    return HttpResponseRedirect( reverse( 'accounts:message_all' ) )


@must_be_staff
def set_moderator( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    user.is_moderator = not user.is_moderator
    user.save()

    if user.is_moderator:
        message = "'{}' is now a moderator.".format( user.username )

    else:
        message = "'{}' is not a moderator anymore.".format( user.username )

    utilities.set_message( request, message )

    return HttpResponseRedirect( user.get_url() )


def password_changed( request ):

    utilities.set_message( request, 'Password changed!' )

    return HttpResponseRedirect( reverse( 'home' ) )


@must_be_staff
def remove_user_confirm( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    context = {
        'user_to_remove': user
    }

    return render( request, 'accounts/remove_user.html', context )


@must_be_staff
def remove_user( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        utilities.set_message( request, "'{}' user removed!".format( user.username ) )
        user.delete()

        return HttpResponseRedirect( reverse( 'index' ) )


@must_be_moderator
def disable_user_confirm( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_disable': user
        }

        return render( request, 'accounts/disable_user.html', context )


@must_be_moderator
def disable_user( request, username ):

    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        value = not user.is_active

            # only other staff users can enable/disable staff users
        if user.is_staff:
            if request.user.is_staff:
                user.is_active = value
                user.save()

            else:
                return HttpResponseForbidden( "Can't disable a staff member." )

        else:
            user.is_active = value
            user.save()


        if value:
            message = "'{}' account is now active.".format( user.username )

        else:
            message = "'{}' account is now disabled.".format( user.username )

        utilities.set_message( request, message )

        return HttpResponseRedirect( user.get_url() )

templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}

<h2>Change password</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:change_password' %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.old_password.label_tag }}</td>
            <td>{{ form.old_password }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password1.label_tag }}</td>
            <td>{{ form.new_password1 }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password2.label_tag }}</td>
            <td>{{ form.new_password2 }}</td>
        </tr>
    </table>

    <input type="submit" value="change" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/check_messages.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}

<h2>Private messages</h2>

{% if messages %}

    <table id="CheckMessagesTable">
        <tr>
            <th>from</th>
            <th>title</th>
            <th>date</th>
        </tr>
        {% for message in messages %}
            <tr class="clickableRow contentPreview" data-url="{{ message.get_url }}" data-content="{{ message.content|linebreaksbr|truncatewords:20 }}">
                <td><a href="{{ message.sender.get_url }}">{{ message.sender }}</a></td>
                <td>{{ message.title|truncatewords:20 }}</td>
                <td>{{ message.date_created|naturaltime }}</td>
                <td><a href="{% url 'accounts:message_remove_confirm' message.id %}">X</a></td>
            </tr>
        {% endfor %}
    </table>

{% else %}
    <p>No messages.</p>
{% endif %}

{% endblock %}

templates/accounts/disable_user.html
{% extends "base.html" %}

{% block content %}

{% if user_to_disable.is_active %}
    <h2>Disable user: {{ user_to_disable }}?</h2>
{% else %}
    <h2>Enable user: {{ user_to_disable }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:disable' user_to_disable.username %}">Yes</a>
    <a href="{{ user_to_disable.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<h1>Login</h1>

{% if form.errors %}
    <p>Wrong username/password.</p>
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

<br /><br />

<p>
    <a href="{% url 'accounts:new_account' %}">Create a new account.</a>
</p>


{% endblock %}

templates/accounts/new_account.html
{% extends "base.html" %}

{% block content %}

    <h1>Create a new user</h1>

    {% if form.errors %}
        <table>
            {% for field in form %}
                <tr>
                    <td>{{ field.name }}</td>
                    <td>{{ field.errors }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

    <form method="post" action="{% url 'accounts:new_account' %}">
        {% csrf_token %}

        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.email.label_tag }}</td>
                <td>{{ form.email }}</td>
            </tr>
            <tr>
                <td>{{ form.password1.label_tag }}</td>
                <td>{{ form.password1 }}</td>
            </tr>
            <tr>
                <td>{{ form.password2.label_tag }}</td>
                <td>{{ form.password2 }}</td>
            </tr>
        </table>

        <input type="submit" value="create" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

{% endblock %}

templates/accounts/open_message.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>From {{ private_message.sender|account_name }} {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>

<a href="{% url 'accounts:message_send' private_message.sender %}">reply</a>
<a href="{% url 'accounts:message_all' %}">back</a>

{% endblock %}

templates/accounts/remove_message.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}

<p>From <a href="{{ private_message.sender.get_url }}">{{ private_message.sender }}</a> {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>


<p>Remove private message? <a href="{% url 'accounts:message_remove' private_message.id %}">Yes</a> <a href="{% url 'accounts:message_all' %}">No</a></p>

{% endblock %}

templates/accounts/remove_user.html
{% extends "base.html" %}

{% block content %}
<h2>Remove user: {{ user_to_remove }} (as well as his posts/etc)?</h2>

<p>
    <a href="{% url 'accounts:remove' user_to_remove.username %}">Yes</a>
    <a href="{{ user_to_remove.get_url }}">No</a>
</p>
{% endblock %}

templates/accounts/send_message.html
{% extends "base.html" %}

{% block content %}

<h2>Send message to {{ username }}</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:message_send' username %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.title.label_tag }}</td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td>{{ form.content.label_tag }}</td>
            <td>{{ form.content }}</td>
        </tr>
    </table>

    <input type="submit" value="send" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/user_page.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<h2>
    Username: {{ pageUser|account_name }}


    <ul class="horizontalList">
        {% if user.is_moderator or user.is_staff %}
        <li>
            <a href="{% url 'accounts:disable_confirm' pageUser.username %}">
                {% if pageUser.is_active %}
                    disable
                {% else %}
                    enable
                {% endif %}
            </a>
        </li>
        {% endif %}

        {% if user.is_staff %}
        <li>
            <a href="{% url 'accounts:set_moderator' pageUser.username %}">
                {% if pageUser.is_moderator %}
                    un-mod
                {% else %}
                    mod
                {% endif %}
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:remove_confirm' pageUser.username %}">remove</a>
        </li>
        {% endif %}
    </ul>
</h2>

<p>Joined: {{ pageUser.date_joined }} ({{ pageUser.date_joined|naturaltime }})</p>

{% if user.is_authenticated %}

    {% if user.username == pageUser.username %}
        <ul>
            <li><a href="{% url 'accounts:message_all' %}">See messages.</a></li>
            <li><a href="{% url 'accounts:change_password' %}">Change password.</a></li>
        </ul>
    {% else %}
        <ul>
            <li><a href="{% url 'accounts:message_send' pageUser.username %}">Send private message.</a></li>
        </ul>
    {% endif %}
{% endif %}

<h3>Last posts (total: {{ total_posts }})</h3>

{% if last_posts %}
    <table class="UserPageTable">
        {% for post in last_posts %}
            <tr>
                <td><a href="{{ post.get_url }}">{{ post.text|truncatechars:20 }}</a></td>
                <td><a href="{{ post.thread.get_url }}">{{ post.thread }}</a></td>
                <td>{{ post.date_edited|naturaltime }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No posts.</p>
{% endif %}

<h3>Last threads (total: {{ total_threads }})</h3>

{% if last_threads %}
    <table class="UserPageTable">
        {% for thread in last_threads %}
            <tr>
                <td><a href="{{ thread.get_url }}">{{ thread.title|truncatechars:20 }}</a></td>
                <td>posts: {{ thread.get_post_count }}</td>
                <td>{{ thread.date_edited|naturaltime }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No threads.</p>
{% endif %}


{% endblock %}