accounts/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',

    url( r'^new_account$', 'accounts.views.new_account', name= 'new_account' ),
    url( r'^login$', 'accounts.views.login', name= 'login' ),
    url( r'^logout$', 'django.contrib.auth.views.logout', name= 'logout' ),
    url( r'^user/(?P<username>\w+)$', 'accounts.views.user_page', name= 'user_page' ),
    url( r'^set_moderator/(?P<username>\w+)$', 'accounts.views.set_moderator', name= 'set_moderator' ),

        # Remove Account

    url( r'^remove/confirm/(?P<username>\w+)$', 'accounts.views.remove_user_confirm', name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', 'accounts.views.remove_user', name= 'remove' ),

        # Disable Account

   url( r'^disable/confirm/(?P<username>\w+)$', 'accounts.views.disable_user_confirm', name= 'disable_confirm' ),
   url( r'^disable/(?P<username>\w+)$', 'accounts.views.disable_user', name= 'disable' ),

        # Change Password
    url( r'^change_password$', 'django.contrib.auth.views.password_change', { 'template_name': 'accounts/change_password.html', 'post_change_redirect': 'accounts:password_changed' }, name= 'change_password' ),
    url( r'^password_changed$', 'accounts.views.password_changed', name= 'password_changed' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', 'accounts.views.message_send', name= 'message_send' ),
    url( r'^message/all/$', 'accounts.views.message_all', name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', 'accounts.views.message_open', name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', 'accounts.views.message_remove_confirm', name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', 'accounts.views.message_remove', name= 'message_remove' ),
)

forum/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [

    url( r'^$', 'forum.views.index', name= 'index' ),
    url( r'^forum/(?P<forumSlug>[\w-]+)/(?P<page>[0-9]+)$', 'forum.views.sub_forum', name= 'subForum' ),
    url( r'^thread/(?P<threadSlug>[\w-]+)/(?P<page>[0-9]+)$', 'forum.views.open_thread', name= 'thread' ),

    url( r'^new_thread/(?P<forumSlug>[\w-]+)$', 'forum.views.new_thread', name= 'new_thread' ),
    url( r'^new_category$', 'forum.views.new_category', name= 'new_category' ),
    url( r'^new_sub_forum/(?P<categorySlug>[\w-]+)$', 'forum.views.new_sub_forum', name= 'new_sub_forum' ),

    url( r'^lock_thread/(?P<threadSlug>[\w-]+)$', 'forum.views.lock_thread', name= 'lock_thread' ),

    url( r'^edit_post/(?P<postId>\w+)$', 'forum.views.edit_post', name= 'edit_post' ),
    url( r'^edit_thread/(?P<threadSlug>[\w-]+)$', 'forum.views.edit_thread', name= 'edit_thread' ),
    url( r'^edit_category/(?P<categorySlug>[\w-]+)$', 'forum.views.edit_category', name= 'edit_category' ),
    url( r'^edit_sub_forum/(?P<forumSlug>[\w-]+)$', 'forum.views.edit_sub_forum', name= 'edit_sub_forum' ),

    url( r'^remove/post_confirm/(?P<postId>\w+)$', 'forum.views.remove_post_confirm', name= 'remove_post_confirm' ),
    url( r'^remove/post/(?P<postId>\w+)$', 'forum.views.remove_post', name= 'remove_post' ),
    url( r'^remove/thread_confirm/(?P<threadSlug>[\w-]+)$', 'forum.views.remove_thread_confirm', name= 'remove_thread_confirm' ),
    url( r'^remove/thread/(?P<threadSlug>[\w-]+)$', 'forum.views.remove_thread', name= 'remove_thread' ),
    url( r'^remove/sub_forum_confirm/(?P<forumSlug>[\w-]+)$', 'forum.views.remove_sub_forum_confirm', name= 'remove_sub_forum_confirm' ),
    url( r'^remove/sub_forum/(?P<forumSlug>[\w-]+)$', 'forum.views.remove_sub_forum', name= 'remove_sub_forum' ),
    url( r'^remove/category_confirm/(?P<categorySlug>[\w-]+)$', 'forum.views.remove_category_confirm', name= 'remove_category_confirm' ),
    url( r'^remove/category/(?P<categorySlug>[\w-]+)$', 'forum.views.remove_category', name= 'remove_category' ),

    url( r'^users_list$', 'forum.views.users_list', name= 'users_list' ),

    url( r'^accounts/', include( 'accounts.urls', namespace= 'accounts', app_name= 'accounts' ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]


    # Serve static files when debug false
if not settings.DEBUG:
    urlpatterns += [
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT } ),
    ]

templates/base.html
{% load static %}
{% load accounts %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Forum</title>

    <script type="text/javascript" src="{% static 'js/tooltip.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/check_messages.js' %}"></script>

    {% block scripts %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>

<div id="Menu">
    <ul class="horizontalList">
        <li>
        {% if user.is_authenticated %}
            Welcome, {{ user|account_name }} ( <a href="{% url 'accounts:logout' %}?next={{ request.get_full_path|urlencode }}">logout</a> )
        {% else %}
            <a href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}">Login</a>
        {% endif %}
        </li>
    </ul>

    <ul class="horizontalList">
        <li><a href="{% url 'index' %}">home</a></li>
        {% for path in paths %}
            <li><a href="{{ path.get_url }}">{{ path|truncatechars:20 }}</a></li>
        {% endfor %}
    </ul>
</div>


{% if MESSAGE %}
    <p id="Message">{{ MESSAGE }}</p>
{% endif %}


{% block content %}{% endblock %}

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

{% if user.is_staff %}
    <ul>
        <li><a href="{% url 'new_category' %}">New category</a></li>
    </ul>
{% endif %}

{% if categories %}

    {% for category in categories %}

        <h2 class="CategoryName">{{ category.name }}</h2>
        {% if user.is_staff %}
            <p>
                <a href="{% url 'new_sub_forum' category.slug %}">New sub-forum</a>
                <a href="{% url 'edit_category' category.slug %}">edit</a>
                <a href="{% url 'remove_category_confirm' category.slug %}">remove</a>
            </p>
        {% endif %}

        {% if category.subforum %}
            <table id="CategoryTable">
            {% for subforum in category.subforum %}
                <tr class="clickableRow" data-url="{{ subforum.url }}">
                    <td><a href="{{ subforum.url }}">{{ subforum.name }}</a></td>
                    <td>threads: {{ subforum.threads_count }}</td>
                    <td>latest post:
                        {% if subforum.last_post %}
                            <a href="{{ subforum.last_post.get_url }}">{{ subforum.last_post.text|truncatechars:10 }}</a> by {{ subforum.last_post.user|account_name }} {{ subforum.last_post.date_created|naturaltime }}
                        {% else %}
                            ---
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>No sub-forums.</p>
        {% endif %}

    {% endfor %}

{% else %}

    <p>No categories.</p>

{% endif %}

<footer>
    <a href="/users_list">users list</a>
</footer>

{% endblock %}

templates/sub_forum.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>
    <a href="{% url 'new_thread' forumSlug %}">New Thread</a>
    {% if user.is_staff %}
        <a href="{% url 'edit_sub_forum' forumSlug %}">edit</a>
        <a href="{% url 'remove_sub_forum_confirm' forumSlug %}">remove</a>
    {% endif %}
</p>

<p>
{% for pageNumber in pages %}
    <a href="{% url 'subForum' forumSlug pageNumber %}" class="PageLink">
        {% if pageNumber == page %}
            <em>{{ pageNumber }}</em>
        {% else %}
            {{ pageNumber }}
        {% endif %}
    </a>
{% endfor %}
</p>

{% if threads %}
    <table id="SubForumTable">
    {% for thread in threads %}
        <tr class="clickableRow contentPreview" data-url="{{ thread.get_url }}" data-content="{{ thread.text|truncatechars:50 }}">
            <td><a href="{{ thread.get_url }}">{{ thread.title|truncatechars:30 }}</a></td>
            <td>by {{ thread.user|account_name }}</td>
            <td>posts: {{ thread.get_post_count }}</td>
            <td>lastest post:
                {% if thread.get_last_post %}
                    <a href="{{ thread.get_last_post.get_url }}">{{ thread.get_last_post.text|truncatechars:10 }}</a> by {{ thread.get_last_post.user|account_name }} {{ thread.get_last_post.date_created|naturaltime }}
                {% else %}
                    ---
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>

    <p>
    {% for pageNumber in pages %}
        <a href="{% url 'subForum' forumSlug pageNumber %}" class="PageLink">
            {% if pageNumber == page %}
                <em>{{ pageNumber }}</em>
            {% else %}
                {{ pageNumber }}
            {% endif %}
        </a>
    {% endfor %}
    </p>

{% else %}
    <p>No threads.</p>
{% endif %}
{% endblock %}

templates/thread.html
{% extends "base.html" %}
{% load humanize %}
{% load emotes %}
{% load accounts %}

{% block content %}
{% if thread %}

<p>
{% for pageNumber in pages %}
    <a href="{% url 'thread' threadSlug pageNumber %}" class="PageLink">
        {% if pageNumber == page %}
            <em>{{ pageNumber }}</em>
        {% else %}
            {{ pageNumber }}
        {% endif %}
    </a>
{% endfor %}
</p>

<table id="ThreadTable">
    <caption>{{ thread.title }}</caption>

    <tr id="post_0" class="ThreadRow">
        <td class="ThreadLeft">
            {{ thread.user|account_name }} {{ thread.date_created|naturaltime }}<br />
            {{ thread.user.get_post_count }} posts
        </td>
        <td class="ThreadRight">
            {{ thread.text|striptags|add_emotes|safe|linebreaksbr }}

            <ul class="postMenu">
                {% if thread.was_edited %}
                    <li>edited by {{ thread.edited_by|account_name }}: {{ thread.date_edited|naturaltime }}</li>
                {% endif %}

                {% if user == thread.user or user.has_moderator_rights %}
                    <li><a href="{% url 'edit_thread' thread.slug %}">edit</a></li>
                {% endif %}
                {% if user.has_moderator_rights %}
                    <li><a href="{% url 'lock_thread' thread.slug %}">
                        {% if thread.is_locked %}
                            unlock
                        {% else %}
                            lock
                        {% endif %}
                    </a></li>
                    <li><a href="{% url 'remove_thread_confirm' thread.slug %}">remove</a></li>
                {% endif %}
            </ul>
         </td>
    </tr>


{% if posts %}
    {% for post in posts %}
    <tr id="post_{{ forloop.counter }}" class="PostRow">
        <td class="ThreadLeft">
            {{ post.user|account_name }} {{ post.date_created|naturaltime }}<br />
            {{ post.user.get_post_count }} posts
        </td>
        <td class="ThreadRight">
            {{ post.text|striptags|add_emotes|safe|linebreaksbr }}

            <ul class="postMenu">
                {% if post.was_edited %}
                    <li>edited by {{ post.edited_by|account_name }}: {{ post.date_edited|naturaltime }}</li>
                {% endif %}

                {% if user == post.user or user.has_moderator_rights %}
                    <li><a href="{% url 'edit_post' post.id %}">edit</a></li>
                {% endif %}
                {% if user.has_moderator_rights %}
                    <li><a href="{% url 'remove_post_confirm' post.id %}">remove</a></li>
                {% endif %}
            </ul>
        </td>
    </tr>
    {% endfor %}
{% endif %}
</table>

<p>
{% for pageNumber in pages %}
    <a href="{% url 'thread' threadSlug pageNumber %}" class="PageLink">
        {% if pageNumber == page %}
            <em>{{ pageNumber }}</em>
        {% else %}
            {{ pageNumber }}
        {% endif %}
    </a>
{% endfor %}
</p>

{% if thread.is_locked %}
    <p>Thread is locked.</p>
{% else %}
    {% if user.is_authenticated %}
        {% if form.errors %}
            <p>{{ form.errors }}</p>
        {% endif %}
        <form id="ThreadPostForm" method="post" action="{% url 'thread' threadSlug page %}">
            {% csrf_token %}

            {{ form.text }}

            <input type="submit" value="post" />
            <input type="hidden" name="next" value="{{ next }}" />
        </form>
    {% else %}
        <p>Need to login to post.</p>
    {% endif %}
{% endif %}

{% else %}
    <p>No thread.</p>
{% endif %}
{% endblock %}

templates/users_list.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if users %}
    <h2>Users List</h2>

    <ul class="horizontalList">
        {% for user in users %}
            <li>{{ user|account_name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No users yet.</p>
{% endif %}

{% endblock %}